CREATE TABLE THECHESS.USUARIO (
    ID BIGINT,
    UUID UUID NOT NULL DEFAULT uuid_in(md5(random()::text || clock_timestamp()::text)::cstring),
    NICKNAME CHARACTER VARYING(255) NOT NULL,
    EMAIL CHARACTER VARYING(255) NOT NULL,
    SENHA CHARACTER VARYING(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT NOW(),
    DATA_EXCLUSAO TIMESTAMP,
    DATA_INATIVACAO TIMESTAMP,
    TIPO_CONTA CHARACTER VARYING(30),
    CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE THECHESS.USUARIO_ID_SEQUENCE;

CREATE UNIQUE INDEX USUARIO_UUID_UK_INDEX ON THECHESS.USUARIO (UUID);
CREATE UNIQUE INDEX USUARIO_UUID_NICKNAME ON THECHESS.USUARIO (NICKNAME);
