ALTER TABLE THECHESS.USUARIO ADD COLUMN TOKEN_RESET_SENHA UUID;
ALTER TABLE THECHESS.USUARIO ADD COLUMN DATA_SOLICITACAO_TOKEN_RESET_SENHA TIMESTAMP;
ALTER TABLE THECHESS.USUARIO ADD COLUMN DATA_RESET_SENHA TIMESTAMP;
ALTER TABLE THECHESS.USUARIO ADD COLUMN DATA_VALIDADE_TOKEN_RESET_SENHA TIMESTAMP;